### ISSUE TITLE
Integer overflow possible for large expressions

### ISSUE THREAD

**Issue by krelinga** [krelinga/rpgeeves#5]
http://rpgeeves-app.appspot.com/dice?d=4832478913742463789124378124378124637120467381246781234678123467891234789017408917469081237469123478902374-891234812379123748912468123647816781230657891235678912367894231d43024823083409

-> 

Traceback (most recent call last):
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/**init**.py", line 511, in **call**
    handler.get(*groups)
  File "/base/data/home/apps/rpgeeves-app/1.345558282811469738/dice/main.py", line 25, in get
    entries = expression.Evaluate(d)
  File "/base/data/home/apps/rpgeeves-app/1.345558282811469738/dice/expression.py", line 111, in Evaluate
    for i in xrange(dice_cnt):
OverflowError: long int too large to convert to int

**Comment by krelinga** [comment]
No plans to work on this
